---
AllCops:
  NewCops: disable
  TargetRubyVersion: 3.0
  Exclude:
    - vendor/**/*
  # enable detailed explanations available in cops
  # the default output is not enough to understand what is wrong
  DisplayCopNames: true
  ExtraDetails: true
  DisplayStyleGuide: true

  # the default CacheRootDirectory is no longer `/tmp`, but a directory under
  # `$HOME` and some Unix platforms use symlink to that path
  AllowSymlinksInCacheRootDirectory: true

Style/OpenStructUse:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  # perefer brackets for `grep-ability`
  EnforcedStyle: brackets

Metrics/BlockLength:
  Exclude: []
  AllowedMethods: []

Layout/LineLength:
  Exclude: []
  # ignore heredoc for readability
  AllowHeredoc: true
  # URLs are almost always long
  AllowURI: true
  URISchemes:
    - http
    - https
    - git
    - ftp
  IgnoreCopDirectives: true
